# Generated by Django 4.2.13 on 2024-06-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
